- name: Create Github Repository
  hosts: localhost
  gather_facts: no
  vars_files:
    - secrets.yml
  tasks:
    # - name: Generate JSON Body for Jinja2 template
    #   set_fact:
    #     repo_body: "{{ lookup('template', 'github_repo_body.j2') }}"

    - name: Create Github Repositories
      uri: 
        url: "{{ github_api_url }}"
        method: POST
        # body: "{{ repo_body }}"
        body_format: json
        body:
          name: "{{ repo_name }}"
          description: "{{ repo_description }}"
          private: "{{ repo_private }}"
          auto_init: true

        headers:
          Authorization: "token {{ github_token }}"
          Content-Type: "application/json"
        status_code: 201
      register: response
    - name: Print API Response
      debug:
        var: response.json

    - name: Delete Repository
      uri:
        url: "{{ delete_repo_url }}"
        method: DELETE
        headers:
          Authorization: "token {{ github_token }}"
          Accept: "Application/vnd.github+json"
        status_code: 204
      register: response_delete

    - name: Print API Response
      debug:
        var: response_delete.status 

    - name: List public repository
      uri:
        url: "{{ list_github_url }}"
        method: GET
        headers:
          Authorization: "token {{ github_token }}"
          Accept: "Application/vnd.github+json"
        status_code: 200
      register: repos_list_reponse

    - name: PRINT LIST OF REPOSITORIES 
      debug:
        msg: "{{ (repos_list_reponse.json | map(attribute='name') | list)[1] }}"  

    - name: PRINT LIST OF REPOSITORIES 
      debug:
        msg: "{{ repos_list_reponse.json | map(attribute='full_name') | list }}"






   