---
- hosts: DBA
  become: yes
  tasks: 
    - name: Update OS
      apt:
        update_cache: yes
        state: present
        
    - name: Install Nginx
      apt:
        name: nginx
        state: present