---
- hosts: webservers
  become: yes
  tasks: 
    - name: Update OS
      apt:
        update_cache: yes
        state: present
        
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      notify: restart nginx

    - name: Deploy NGINX Configuration
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default

    - name: Create simple HTML
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
            <title>Welcome to work</title>
          <head>
          <body>
            <h1> Ansible is cool</h1>
            <h1> This page is managed with Ansible</h1>
          <body>
          <html>
        dest: /var/www/html/site.html
        mode: "0644"


