---
all:
  children:
    web_servers:
      hosts:
        13.73.55.170:
      vars:
        ansible_ssh_private_key_file: /home/mosesugwu/.ssh/moseskey

    php_servers:
      hosts:
        13.73.36.31:
      vars:
        ansible_ssh_private_key_file: /home/mosesugwu/.ssh/moseskey

    database:
      hosts:
        13.73.32.141:
      vars:
        ansible_ssh_private_key_file: /home/mosesugwu/.ssh/moseskey

#Nested Groups
    Production:
      children:
        php_servers:

    Development:
      children:
        web_servers:

    DBA:
      children:
        database: