---
all:
  children:
    web_servers:
      hosts:
        13.83.88.183:
      vars:
        ansible_ssh_private_key_file: /home/mosesugwu/.ssh/moseskey

    php_servers:
      hosts:
        13.91.217.212:
      vars:
        ansible_ssh_private_key_file: /home/mosesugwu/.ssh/moseskey

    database:
      hosts:
        13.83.94.187:
      vars:
        ansible_ssh_private_key_file: /home/mosesugwu/.ssh/moseskey

#Nested Groups
    Production:
      children:
        php_servers:

    Development:
      children:
        web_servers:

    DBA:
      children:
        database: