---
# tasks file for docker
- name: Update OS
  apt: 
    update_cache: yes
    state: latest

- name: Install Cert. and Curl
  apt: 
    name: "{{ item }}" 
    state: latest
  loop:
    - ca-certificates
    - curl

- name: Add Docker GPG key directory
  file:
    path: "{{ key_dir }}"
    state: directory
    mode: "0755"

- name: Add Docker GPG key
  get_url:
    url: "{{ docker_url }}"
    dest: "{{ key_dest }}"
    mode: "0644"

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present
    update_cache: yes

- name: Install the Docker packages
  apt:
    update_cache: true
    state: present 
    name: "{{ item }}"
  loop: 
    - docker-ce 
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
